version: v0.4-alpha.{build}
configuration:
- Debug
- Release
platform: x86
build:
  project: EDU Game Engine.sln
  verbosity: normal
before_package:
- ps: Copy-Item C:\projects\edu-game-engine\$env:CONFIGURATION\Engine.exe C:\projects\edu-game-engine\Game\.
artifacts:
- path: Game
  name: game_files
deploy:
- provider: GitHub
  description: Test release
  auth_token:
    secure: jQJuY3qrofMwGeeOI09t523try6rsIrOkdIIEpLQN6gHcn3ypWKa55gdEMPR1bik
  artifact: game_files
  draft: false
  prerelease: true
  force_update: true
  on:
    CONFIGURATION: Release
